feature: 엔티티 생성
Leets-Official/Carrot-BE pull request #2
Opened 2024-09-29 17:01 UTC by codingmy

## 1. 무슨 이유로 코드를 변경했나요?
엔티티를 생성하고자 작업
<br>

## 2. 어떤 위험이나 장애를 발견했나요?
sql이 픽스되지 않은 상태에서 엔티티를 생성하는 상황이라 변수명이나 erd상에서 대강 잡아놓은 부분이 있어 작업 중 변경될 수 있는 부분이 많다고 판단되 일단 1차적으로 간략하게 생성해놓았습니다~ 각자 api 구현하면서 수정이 필요한 부분은 수정해서 구현하는 것을 목표로 엔티티를 설계해놓았습니다! 참고바랍니당

도, 시, 디테일한 지역 정보 관련해서는 이 세 테이블 내부 구조가 동일해 추상클래스를 이용하는 구조로 설계해보았습니다 혹시 더 좋은 구조나 방법이 있으시다면 리뷰바랍니당
<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항
존재하는 엔티티 모두 생성 완료
<br>

## 5. 추가 사항

2024-10-01 14:19 UTC, huncozyboy reviewed
엔티티 작성하시느라 수고 많으셨습니다 👏👏

2024-10-01 14:19 UTC, huncozyboy commented on src/main/java/land/leets/Carrot/domain/user/entity/User.java
> +}
로그인 회원가입 기능을 넣으려면 엔티티에 로그인 할 수 있는 아이디랑 비밀번호가 있는게 좋아보입니당~~ 이건 프론트랑 회의 후 sql 픽스 낼때 같이 얘기해봐요

2024-10-01 14:19 UTC, huncozyboy commented on src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
> +    private long phoneNumber;
전화번호의 변수형은 long 보다는 string이 좋을거같습니다 !!

2024-10-01 14:19 UTC, huncozyboy commented on src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
> +    private boolean isSundaySelected;
요일들을 Enum으로 묶어서 dayOfWeek라는 이름으로 따로 빼는것도 좋아보여요

2024-10-01 14:19 UTC, huncozyboy commented on src/main/java/land/leets/Carrot/domain/review/entity/Review.java
> +    private long applyId;
ERD상 review 테이블이랑 apply 테이블이 다대일로 연결되어 있기 때문에 Review 엔티티에서 @ManyToOne으로 연관관계 설정을 나중에 추가하시면 좋을거같아용

2024-10-01 14:43 UTC, codingmy commented on src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
> +    private long phoneNumber;
안그래도 이거에 대해서는 저도 고민을 했던 부분인데요! 프론트에서 전화번호를 유저한테 어떤 입력 방식으로 어떻게 받아오냐에 따라서 달라질 것 같아서 조금 문제더라고요ㅠ

예를들어 프론트에서 아예 String으로 받는 경우에는 유저가 하이픈을 맘대로 넣거나 빼놓던가 하는 경우의 수가 생겨서(010-XXXX-XXXX이 정식이지만 010XXXXXXXX이렇게 써버릴 수도 있고 010-XXXXXXXX 이렇게 하이픈을 맘대로 빼먹고 쓰는 경우 다 가능), 프론트에서 주는 String 값을 바로 db에 String 으로 저장하기에는 쪼금 데이터 형태에 일관성이 없어서 적절하지 않을 것 같다는 생각이었습니당

근데 아직 프론트에서 전화번호에서는 전처리를 해서 백엔드로 전달해주는지 이 부분이 조율이 안된 상황이라, 변수형을 픽스하기 어렵더라고요.ㅠ 그래서 일단 어떻게 프론트에서 넘어오든 먼저 백엔드 단에서는 전화번호 데이터의 형태의 일관성을 지킬 수 있도록 전화번호를 프론트에서 받았을 때, 받은 전화번호를 무조건 백엔드 단에서 하이픈 유무를 확인 및 제거하는 과정을 무조건 거치는 로직을 생각해서 long으로 결정해서 설계를 해놓은 상황이긴한데, 이 문제에 대해서 지훈님의 의견도 궁금합니당!

2024-10-01 14:48 UTC, codingmy commented on src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
> +    private boolean isSundaySelected;
앗 이 부분이 근무요일 관련해서 근무하는 요일만 true 값을 갖도록 해서 모든 근무 요일의 경우의 수(월만 근무, 월수금 근무, 월화목 근무, 월 토 근무.... 등등 모든 근무 경우의 수)에 대해서 기록할 수 있도록 이렇게 설계했었던 부분인데용 enum으로 요일을 묶는다는 부분을 이해하지 못해서 조금 자세히 설명해주실 수 있을까용?

2024-10-01 14:51 UTC, codingmy commented on src/main/java/land/leets/Carrot/domain/user/entity/User.java
> +}
어라 그렇네요?!?! erd 확인해보니까 저희 erd때 부터 빠뜨렸던 부분이네용ㅋ큐ㅠ 넹 그때 얘기해봅시당

2024-10-08 13:54 UTC, huncozyboy commented on src/main/java/land/leets/Carrot/domain/location/entity/AreaBaseEntity.java
> +@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
해당 부분의 `@Inheritance` 어노테이션으로 인해서 빌드과정에서 오류가 나고 있는데 혹시 사용하신 이유가 있으실까요?
`@Inheritance` 어노테이션을 찾아보니까 매퍼가 필요한걸로 알고 있어서, 저희 엔티티 구조에서는 맞지 않는거같아서 수정이 필요해보입니다 !

2024-10-08 16:17 UTC, codingmy commented on src/main/java/land/leets/Carrot/domain/location/entity/AreaBaseEntity.java
> +@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
지역 관련한 엔티티들 SiArea, DoArea, DetailArea의 세 엔티티들이 형태가 모두 동일하다는 점에서 추상클래스를 생성해서 구현하는 방법이 좀더 적절할 것 같아 추상클래스로 구현하는 방법으로 결정하였는데요. 
querydsl 을 사용할지, jpa를 사용할지 결정이 안된 상황에서 추상클래스를 구현하던 중 들어간 것 같아요! 해당 어노테이션 삭제했습니다!

2024-10-09 08:23 UTC, rootTiket reviewed
구현하느라 고생하셨습니다 :) 
제가 생각했을 때 이것도 생각해보면 좋을것 같은데?! 싶은 부분에 코멘트를 남겨두었으니 참고해보시면 좋을것 같아요! 😄

2024-10-09 08:23 UTC, rootTiket commented on src/main/java/land/leets/Carrot/domain/location/entity/DoArea.java
> +}
아래를 쭉 읽어보니까 Area는 모두 같은 필드값을 가지네요! 
Area라는 추상 클래스를 만들고 이를 상속 받아 구현하는것은 어떨까요?
```java
@Getter
@MappedSuperclass
public abstract class Area {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int areaId;

    private String name;
}

@Entity
public class DoArea extends Area {
    // 필요 시 추가 필드 및 메서드 정의
}

@Entity
public class SiArea extends Area {
    // 필요 시 추가 필드 및 메서드 정의
}

```

이렇게하면 중복코드를 없애고 만약 각 시 도 동 필드에 변경이 생긴다고 하면 한번에 변경 할 수 있어 기능 변경에 더 유리할 수 있을것 같아요 :) 
생각해보시면 좋을것 같습니당 !

2024-10-09 08:23 UTC, rootTiket commented on src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
> +    private boolean isSundaySelected;
```java
public enum DayOfWeek {
    MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
}

private Set<DayOfWeek> selectedDays = EnumSet.noneOf(DayOfWeek.class);

    public void selectDay(DayOfWeek day) {
        selectedDays.add(day);
    }

    public void deselectDay(DayOfWeek day) {
        selectedDays.remove(day);
    }

    public boolean isDaySelected(DayOfWeek day) {
        return selectedDays.contains(day);
    }

    public Set<DayOfWeek> getSelectedDays() {
        return selectedDays;
    }

```

이런식으로 enum으로 구현해서 요일을 입력 -> 해당 요일이 선택됨
으로 로직을 구성하면 직관적 일 수 있을것 같네요!
선택된 요일들을 List나 Set으로 관리(순서가 관계없다면 set이 더 좋아보입니다 ), 필드 자체도 줄일 수 있어 db관리에도 용이할 것 같다는 생각입니다! 
생각해보시고 의견 남겨주세요 👍

2024-10-09 08:28 UTC, rootTiket commented on src/main/java/land/leets/Carrot/domain/location/entity/DoArea.java
> +}
앗 위 코멘트 확인을 못했었네요
@MappedSuperclass 어노테이션을 사용하면 추상 클래스로 구현 가능할 것 같아서 고려해보시면 좋을것 같습니다 !

2024-10-09 08:43 UTC, yechan-kim requested changes
고생하셨습니다! 코드를 읽고 궁금한 점이나 개선하면 좋겠는 사항들을 적어놨으니 확인 부탁드립니다!

전반적으로 원시 타입을 사용하는데, 원시 타입은 기본값이 자동으로 설정되기 때문에 데이터의 상태를 명확히 파악하기 어렵고, DB에서 `null`을 처리할 때 문제가 발생할 수 있습니다. 따라서 `Integer와 같은 참조 타입을 사용하는 것을 권장합니다.

또한 ERD를 보면 `1:N`관계가 보이는데 이러한 것들은 `JPA`에 있는 `@ManyToOne`이나 `@OneToMany` 어노테이션을 활용하는 것을 추천합니다!

2024-10-09 08:43 UTC, yechan-kim commented on src/main/java/land/leets/Carrot/domain/apply/entity/Apply.java
> +    private Timestamp viewAt;
`Timestamp`은 JAVA의 `Legacy Class`입니다. `Modern class`인 `LocalDateTime`를 추천합니다!
혹시 `Timestamp`를 사용하신 이유가 있으실까요?

2024-10-09 08:43 UTC, yechan-kim commented on src/main/java/land/leets/Carrot/domain/apply/entity/Apply.java
> +    private boolean isResponsed = false;
자바 빈 규칙에 따르면, `boolean` 필드의 `getter`는 `is`로 시작하는 것이 맞지만, 필드 이름에 `is`를 포함시키면 중복이 발생할 수 있습니다. 따라서 필드명을 변경하는 것을 추천합니다!

2024-10-09 08:43 UTC, yechan-kim commented on src/main/java/land/leets/Carrot/domain/career/entity/Career.java
> +    private int endDate;
날짜 데이터는 `LocalDate` 타입으로 관리하는 게 좋아 보이는데 혹시 따로 분리하신 이유가 있을까요?

2024-10-09 08:43 UTC, yechan-kim commented on src/main/java/land/leets/Carrot/domain/career/entity/WorkType.java
> +}
`Type`같은 경우는 `class`보다는 `Enum`으로 관리하는 게 좋아 보이는데 어떻게 생각하시나요?

2024-10-09 08:43 UTC, yechan-kim commented on src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
> +    private String image;
이 부분에는 `url`만 들어갈 것 같은데, `url`만 들어간다면 변수명 뒤에 `url`을 붙이는 것이 구별하기 쉬울 것 같습니다!

2024-10-09 08:43 UTC, yechan-kim commented on src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
> +    private long phoneNumber;
일반적으로 전화번호 같은 경우에는 `String` 타입으로 저장하는 걸로 알고 있습니다!
대부분 0으로 시작하기 때문에, 프론트에서 `Long`타입으로 보내주면 나중에 `0`을 븉여주는 번거로움이 생기겠죠?
하이픈 같은 경우에는 프론트에서 하이픈 형식이 틀리면 전송을 못하도록 로직을 구성하면 백엔드에서는 일관된 번호를 받을 수 있습니다! 해당 사항은 타입은 `String`으로 가져가고, 하이픈 형식은 프론트 분들과 같이 협의를 통해 결정하면 될 것 같습니다!

2024-10-09 08:43 UTC, yechan-kim commented on src/main/java/land/leets/Carrot/domain/post/entity/ShortWorkData.java
> +    private Date workDate;
`Date`도 `Legacy Class`입니다. Modern class인 LocalDateTime를 추천합니다!
따로 사용하신 이유가 있다면 그대로 두셔도 됩니다!

2024-10-09 11:48 UTC, merged

2024-10-09 11:51 UTC, codingmy commented on src/main/java/land/leets/Carrot/domain/location/entity/DoArea.java
> +}
원래 pr올릴 때는 추상 클래스를 만들어서 구현하는 방법으로 했었는데 깃헙 cicd 액션에서 오류나는 부분때문에 일단은 삭제해놓은 상태입니다! 나중에 다시 부활시켜보도록 하겠습니다!

2024-10-09 11:54 UTC, codingmy commented on src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
> +    private boolean isSundaySelected;
enumSet타입을 몰랐었는데 알아보니 enumSet으로 저장하게 되면 해당 부분은 필드를 좀더 단순화 시킬 수 있어서 더 적절한 구현 방법인 것 같네요 해당 기능 구현 시에 적용해서 구현해보도록 하겠습니다!

2024-10-09 12:33 UTC, codingmy commented on src/main/java/land/leets/Carrot/domain/apply/entity/Apply.java
> +    private boolean isResponsed = false;
아 이 부분은 고려하지 못했네요 해당 네이밍은 수정하도록 하겠습니다!

2024-10-09 12:40 UTC, codingmy commented on src/main/java/land/leets/Carrot/domain/career/entity/WorkType.java
> +}
이 부분은 회의에서도 언급이 되었던 부분인데요! 
추후 기존의 값을 수정하거나 추가하고 싶을 때 해당 필드를 `enum`으로 관리하게 된다면 코드 자체를 수정해야하는 상황이 발생하는데요. `class`로 관리하게되면 추후 값을 수정할 때 코드의 수정 없이, db에 추가하고 싶은 workType을 string 값으로 갖는 row를 하나 추가하기만 하면 되기 때문에 유지보수적인 측면에서 `enum`보다는 `class`로 관리하는 것이 더 적절하다고 판단해 위와 같이 구현하였는데요 혹시 제가 생각한 방법보다 더 좋은 방법이 있을지 예찬님 시각이 궁금합니다!

2024-10-09 12:41 UTC, codingmy commented on src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
> +    private String image;
그 방법이 네이밍이 더 직관적인 것 같네요! 반영하도록 하겠습니다!

2024-10-09 12:47 UTC, codingmy commented on src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
> +    private long phoneNumber;
앗 하이픈과 관련해서 데이터의 제약조건과 관련한 무결성을 고려해서 숫자만 저장한다는 가정으로 `Long`형식을 사용하는 것으로 결정한거였는데, 일반적으로 0으로 시작한다는 점을 고려하지 못했네용 ㅠ 해당 전화번호 타입은 `String`으로 가져가는 것이 맞는 것 같습니다! 반영하도록 하겠습니당